### ISSUE TITLE
How can i use it as imageview inside another view

### ISSUE THREAD

**Issue by AlexGZC** [tadija/AEImage#1]
How can i use it as imageview inside another view,may you give an example?
Thi is what i have done but i want to add the motion on ImageScroolview(), can i?

       var motionSettings  = MotionSettings()
        let viewDemo = UIView()
        let  imageScrollView = ImageScrollView()
        imageScrollView.displayMode = .fillHeight
        imageScrollView.infiniteScroll = .horizontal
        imageScrollView.enableMotion()
        motionSettings.isEnabled = true
        motionSettings.sensitivity = 1.0
        imageScrollView.image = #imageLiteral(resourceName: "panorama")
        imageScrollView.frame = prueba.bounds
        prueba.addSubview(imageScrollView)

**Comment by tadija** [comment]
Hi @AlexGZC, actually no, since motion feature is implemented only in `ImageViewController` (not in `ImageScrollView`), you should in that case add image view controller as a child view controller in your view controller's view and use it like that.
